[env:esp32-2424S012]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv

extra_scripts = pre:scripts/get_git_revision.py

monitor_speed = 115200
upload_speed = 115200

upload_flags =
    --before=default_reset
    --after=hard_reset

build_flags = 
    -D USER_SETUP_LOADED=1
    -I include
 
    -include include/config.h
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    moononournation/GFX Library for Arduino @ 1.4.0
    https://github.com/h2zero/NimBLE-Arduino
    https://github.com/fbiego/CST816S
